language: java
jdk:
- oraclejdk7
cache:
  directories:
  - .gradle
script:
- ./gradlew build --info --stacktrace
after_success:
- ./gradlew bintrayUpload --info --stacktrace
env:
  global:
  - secure: BhuVGJD/ndYQysIT6dI0TwzOyfyP6GS64x5CTibcIm95yehCjaCrcjElgk0m5SADXJtYOP+Swca+UzAxxeMevP9WiaEN4TAc9baW9/MFBn8pYgu8W+QTo+wfgJU3L6mKGLxujm/Km8cLb5P9R7HB7pISiSw1QmhfZS63EIxLelR3FX2v9OsI3YWqvDjtq6rJ82+Do/BCc9iIJ2UzUd7tOnOYFNXPgwv0iebniOuPlEUH+DJ6zc0nQXyqBeMxfiGrRqePsZhtXl0wJrQN46w1SlfIGYDeqwehAqSVBL+hMZcqrbR46sD9OjWNDprT4LRbjNO+nhyxVxyYU/PV20EFiiDNDUiNOlBA0XdXIqZqCiDhplUu2EbjV7JY00wKjAy+8K2JKaUOEOIxo2B06R7R4Q674MOTI8ytk7pJ/j76wTtsqUQOcYKGXshtUZDq7qT/C/fSFz6IoT65Jli5V8OXM0/MbuoiMl/b9w0j/LvkC3BTGQTv+Sq4Lyd2ZXHvta6KigKAA1l/PH3VqNqVbTkubrVuHZuaTpGYEMVZYQqsM3jOu7bsfmSQ7R9A+HlszoNXTs8bZ6vtUBxASV1lhBcjuCzEtxbF6c2vP0/ZCfLYKtW4vuhpGYfbsatbNZMVP4e3kJCbg6ZO3MPpRg05ohvaM70YZCrfHIcHwjaTIDn//eQ=
  - secure: T11xO/wr492ebMbBPkszj8NmuqLMDIRjATcLXV59QzOPUlE9SSRvKQxpBoU5rPQxK1GKWaykKXN6BtpwUDcCKcZ5CpqsOdnap+wIzb1Z2W5JYm3pC0dkCgSiUGU1d31ZUObObZUAYGAT2bBD0PATLaglAeoz9db3OKOhhWq1T7sz0BZOJHUg1hnnyr5BQdS1XkvMckPzXj2MtaJOQvajdf/iCBA/YinzVsV5WYVYJcqQLA5ki1MqJJ7c6eud4oNnpZJ9keFFFPRcszDuv0l8rRuj8zflyk3MVMBYiG1WX/UrI7gdkCCOINYur0WkHzhBnroOVocpUyGpvINXhrGWW6zCrgwEdoLX61RVJUmqGbeN39GG9kRHvpUnio7H/x2aXVLEnuXLD+fwK+PdmfVtJ7q7MNOXuj8Z2ureT+BF4e0ZajF3kRoNrVwX9xlmx1tuB/OrUYHYOaDPSwmiHizVYDjrmWgLqCi5KyeuuvC+8wMf0cLfU7K1ii2stYzUczkYABRT6B315Ret0t9vqhhMeCg//wMVSnvwolS/6u5jAbzgdbrWxUGQg/nBFuqbyhZTPcLQTOs0zbyZ2RUS49xSENZTBr+Iuuh7NCiNXn1taRy2jPLtrCXbpwMNEyLhLuitlZq7Gj4HsFYKL3HyCs92yxckKfhSkgrCIQx5Ll/cJdw=
